import { User } from '~/entities/User';

export const users: User[] = [
  {
    id: '1',
    email: 'test@mail.io',
    first_name: 'Some',
    last_name: 'User',
    avatar: 'https://www.seiu1000.org/sites/main/files/main-images/camera_lense_0.jpeg',
    username: 'someuser',
    monetization_enabled: false,
    pro_subscribed: false,
    profile_audio_description: null,
    profile_description: '',
    online: false,
    social_logins: [],
    owned_channels: [],
    follower_count: 0,
    following_count: 0,
    verified: false,
  },
  {
    id: '2',
    email: 'test@mail.io',
    first_name: 'Some',
    last_name: 'User',
    avatar: 'https://www.seiu1000.org/sites/main/files/main-images/camera_lense_0.jpeg',
    username: 'someuser',
    monetization_enabled: false,
    pro_subscribed: false,
    profile_audio_description: null,
    profile_description: '',
    online: false,
    social_logins: [],
    owned_channels: [],
    follower_count: 0,
    following_count: 0,
    verified: false,
  },
  {
    id: '3',
    email: 'test@mail.io',
    first_name: 'Some',
    last_name: 'User',
    avatar: 'https://www.seiu1000.org/sites/main/files/main-images/camera_lense_0.jpeg',
    username: 'someuser',
    monetization_enabled: false,
    pro_subscribed: false,
    profile_audio_description: null,
    profile_description: '',
    online: false,
    social_logins: [],
    owned_channels: [],
    follower_count: 0,
    following_count: 0,
    verified: false,
  },
  {
    id: '4',
    email: 'test@mail.io',
    first_name: 'Some',
    last_name: 'User',
    avatar: 'https://www.seiu1000.org/sites/main/files/main-images/camera_lense_0.jpeg',
    username: 'someuser',
    monetization_enabled: false,
    pro_subscribed: false,
    profile_audio_description: null,
    profile_description: '',
    online: false,
    social_logins: [],
    owned_channels: [],
    follower_count: 0,
    following_count: 0,
    verified: false,
  },
  {
    id: '5',
    email: 'test@mail.io',
    first_name: 'Some',
    last_name: 'User',
    avatar: 'https://www.seiu1000.org/sites/main/files/main-images/camera_lense_0.jpeg',
    username: 'someuser',
    monetization_enabled: false,
    pro_subscribed: false,
    profile_audio_description: null,
    profile_description: '',
    online: false,
    social_logins: [],
    owned_channels: [],
    follower_count: 0,
    following_count: 0,
    verified: false,
  },
  {
    id: '6',
    email: 'test@mail.io',
    first_name: 'Some',
    last_name: 'User',
    avatar: 'https://www.seiu1000.org/sites/main/files/main-images/camera_lense_0.jpeg',
    username: 'someuser',
    monetization_enabled: false,
    pro_subscribed: false,
    profile_audio_description: null,
    profile_description: '',
    online: false,
    social_logins: [],
    owned_channels: [],
    follower_count: 0,
    following_count: 0,
    verified: false,
  },
  {
    id: '7',
    email: 'test@mail.io',
    first_name: 'Some',
    last_name: 'User',
    avatar: 'https://www.seiu1000.org/sites/main/files/main-images/camera_lense_0.jpeg',
    username: 'someuser',
    monetization_enabled: false,
    pro_subscribed: false,
    profile_audio_description: null,
    profile_description: '',
    online: false,
    social_logins: [],
    owned_channels: [],
    follower_count: 0,
    following_count: 0,
    verified: false,
  },
  {
    id: '8',
    email: 'test@mail.io',
    first_name: 'Some',
    last_name: 'User',
    avatar: 'https://www.seiu1000.org/sites/main/files/main-images/camera_lense_0.jpeg',
    username: 'someuser',
    monetization_enabled: false,
    pro_subscribed: false,
    profile_audio_description: null,
    profile_description: '',
    online: false,
    social_logins: [],
    owned_channels: [],
    follower_count: 0,
    following_count: 0,
    verified: false,
  },
];
